name: Build

on: [release]

jobs:
  release-darwin-amd64:
    steps: 
    - name: "release darwin/amd64"
      uses: ngs/go-release.action@v1.0.1
      env:
        GOOS: darwin
        GOARCH: amd64
      secrets:
        - GITHUB_TOKEN

